# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build Website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Checkout theme repo
      uses: actions/checkout@v2
      with:
        repository: molivier/nest 
        path: nest

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install theme
      run: |
        pelican-themes --install nest

    - name: Build to gh-pages branch
      run: make github
